#+TITLE: Chris Wallace: code
#+SETUPFILE: ./setup.org

#+INCLUDE: ./nav.org

# Most of my current software is distributed in the form of R packages.
# Published and maintained packages are available
#       from [[http://crantastic.org/authors/2111][CRAN],
# while "in progress" packages, together with intermediate
#   updates of CRAN packages can be found
#   at  [[https://github.com/chr1swallace][github]].
# I put notes, and try and flag updates
#       at my [[http://cwcode.wordpress.com][code blog]</p>


* CRAN packages
*** [[http://cran.r-project.org/web/packages/coloc/index.html][coloc]] 
	  a package of R functions used to test for
	  colocalisation of two genetic traits.  For more detail or
	  the statistical background and applications see:
	  
#+BEGIN_QUOTE
  Wallace et al. Statistical colocalisation of monoyte gene
	    expression and genetic risk variants for type 1
	    diabetes. /Hum Mol Genet/ 2010. [ [[http://europepmc.org/abstract/MED/22403184][Europe PMC]] ]
#+END_QUOTE
	  
#+BEGIN_QUOTE
 Wallace. Statistical testing of shared genetic control for potentially related traits. [ [[http://arxiv.org/abs/1301.5510][arXiv 1301.5510]] ]
#+END_QUOTE
	  
#+BEGIN_QUOTE

	     Giambartolomei et al.  Bayesian test for co-localisation between pairs of genetic association studies using summary statistics. [ [[http://arxiv.org/abs/1305.4022][arXiv 1305.4022]] ]
	#+END_QUOTE
*** [[http://cran.r-project.org/web/packages/snpStatsWriter/index.html][snpStatsWriter]]
	allows writing snpStats objects to disk in formats suitable
	for reading by snphap, phase, mach, IMPUTE, beagle, and
	(almost) anything else that expects a rectangular format.
*** [[http://cran.r-project.org/web/packages/wgsea/index.html][wgsea]] 
implements a
	  Wilcoxon-based test for Gene Set Enrichment Analysis when
	  testing regions of the genome according to GWAS derived
	  evidence for SNP-trait association.  For more detail, see
	  the supplementary methods of	  
#+BEGIN_QUOTE
 A trans-acting locus regulates an anti-viral expression network and type 1
diabetes risk.  Heinig M, et al.  /Nature/ 2010. [ [[http://europepmc.org/abstract/MED/20827270][Europe PMC]] ]
#+END_QUOTE
*** [[http://cran.r-project.org/web/packages/extraBinomial][extraBinomial]]
  (author Xin Yang, listed here because Xin doesn't have her own website)
  uses an extra binomial model to test for case-control
  allele frequency differences in pooled sequence data.  See
#+BEGIN_QUOTE
    Yang X, Todd JA, Clayton D, and Wallace C.
    Extra-binomial variation approach for analysis of pooled DNA sequencing data.
    /Bioinformatics/ 2012.
    [ [[http://europepmc.org/abstract/MED/22976083][Europe PMC]] ]
#+END_QUOTE

* Non-CRAN packages
To install these from github, do, in R:
#+BEGIN_SRC 
install.packages("devtools")
library(devtools)
install_github("chr1swallace/package.name", "chr1swallace")
#+END_SRC
*** [[https://github.com/chr1swallace/annotSnpStats][annotSnpStats]]
       extends SnpMatrix objects from the snpStats package by tying in
       sample and snp annotation data.frames.  It allows the joint
       manipulation, and binding, of such objects, and includes a few
       functions I use for finding duplicate samples, applying QC, and
       aligning alleles between different datasets.  It seems to work,
       and I intend to push it to CRAN in the future.</li>
*** [[https://github.com/chr1swallace/origin][origin]] implements an
  extension to the Weinberg method for testing for parent of origin
  effects to allow for multiple affected offspring in a nuclear
  family.  I haven't used it in a while, and it requires some checking
  just to get it to pass the CRAN tests.  Unless I need to revisit it
  for another reason, I am unlikely to push it to CRAN, but it is a
  finished package.
  For more detail see:
#+BEGIN_QUOTE
 Weinberg et al. Methods for detection of parent-of-origin effects in
    genetic studies of case-parents triads. /Am J Hum Genet/
    65:229-235. 1999.
#+END_QUOTE    
#+BEGIN_QUOTE
    Wallace et al. The imprinted DLK1-MEG3 gene region on chromosome
    14q32.2 alters susceptibility to type 1 diabetes. /Nat
      Genet/ 2010.
    [ [[http://europepmc.org/abstract/MED/19966805][Europe PMC]] ]
#+END_QUOTE

* Older software
*** IBDSCORE [[[soft/ibdscore.tgz][download]]] implements a score test for the Rice-Holmans IBD
	regression model.
	The model is described by

#+BEGIN_QUOTE
 Holmans, P. /Human Heredity/ 2002. 53:92-102
#+END_QUOTE
#+BEGIN_QUOTE
Rice et al. /Genet Epidemiol/ 1999. 17:S691-S695
#+END_QUOTE
and this score test by
#+BEGIN_QUOTE
Wallace et al. /Am J Hum Genet/ 2006. 79:323-31 [ [[http://europepmc.org/abstract/MED/16826522][Europe PMC]] ]
#+END_QUOTE


* See also...

[ [[http://crantastic.org/authors/2111][published R packages on CRAN]] | [[http://github.com/chr1swallace][all code at github]] | [[http://cwcode.wordpress.com][code blog]] ]
