#+TITLE: Postdoctoral Statistician, MRC Biostatistics Unit, Cambridge
#+SETUPFILE: ./setup3.org

#+INCLUDE: ./nav2.org

*Career Development Fellow* (Fixed Term)

MRC Biostatistics Unit, Cambridge

3 years Fixed Term Post 

The MRC Biostatistics Unit undertakes research on statistical methods and their application to the design, analysis and interpretation of biomedical studies, to advance understanding of the cause, natural history and treatment of disease, and to evaluate public health strategies. A research team under the direction of Dr Chris Wallace aims to develop statistical methods for the analysis of genomic data to understand the human immune system and its dysregulation in relation to the autoimmune diseases (e.g. type 1 diabetes and rheumatoid arthritis) which collectively affect 5% of the population.  Our goal is to understand the genes, cells and pathways which underlie autoimmune diseases, the interactions between these pathways, and the relationships between different autoimmune diseases.  Better understanding of the aetiology of these diseases is essential to underpin better treatment strategies.   

We are seeking an ambitious statistician to contribute to this research team.  The proposed initial project focuses on development of latent variable models for genomic regulation, but there exists a wealth of data and the post holder will be encouraged to develop other research interests that are relevant to the goals of the group.  Current members are working across a diverse range of projects including genetic association to disease, mechanisms of genomic regulation and modelling of count data from emerging sequencing-based technologies.  For further information on the group and our research, see http://chr1swallace.github.io.

The groups is based in the MRC Biostatistics Unit (http://www.mrc-bsu.cam.ac.uk) and the University of Cambridge Department of Medicine (http://www.med.cam.ac.uk), both located within the Cambridge Biomedical Campus.  The advertised post will be located in the Biostatistics Unit, but the available interdisciplinary environment offers the applicant the chance to pursue statistical methodology and apply solutions to novel biological datasets in order to address questions of relevance to human autoimmune diseases.  Our group has active collaborations within Cambridge (eg Ken Smith) and the nearby Babraham Institute (Peter Fraser and Mikhail Spivakov), but also with the University of Manchester (Wendy Thomson and Steve Eyre) and UCL (Lucy Wedderburn).  Please contact chris.wallace@mrc-bsu.cam.ac.uk with any informal enquiries.

By the time they take up the appointment, the successful applicant will have a PhD in a strongly quantitative subject, ideally statistics. Experience of managing large datasets and an understanding of genomics are desirable.  Most important are an inquisitive mind and the desire to develop and apply statistical methodology to questions of substantive biological importance and disease relevance.  The successful applicant will be supported in their career development with a range of formal courses and on-the-job training. 

Closing date: 8th November 2016			

[[http://www.jobs.cam.ac.uk/job/11725/][Apply now]]

